### ISSUE TITLE
enum EntityType?

### ISSUE THREAD

**Issue by arthef** [shannah/CodeRAD#14]
I was wondering if there is a way to have enum field type in the Entity. I think it could be worked around with Integer field and takin `ordinal` value of the enum but this seems like a workaround rather than a solution.

Having enum field would be very useful for cases like handling states or status of a protocol flow or other things.

Any suggestions?

**Comment by shannah** [comment]
Would the `object(Class type)` property suffice for this?

I haven't tried this but:

~~~~
public enum Color {
    Red,
    Green,
    Blue;
}
public static final Tag TAG_COLOR = new Tag("Color");
EntityType TYPE = new EntityType() {{
       object(Color.class, TAG_COLOR);
}};
...
~~~~

It is possible I'll need to add some special consideration for data coercion between types, but the basics should already work.

**Comment by arthef** [comment]
Thank you I will experiment with this to find what works best for my use-case.
