### ISSUE TITLE
hasChanged() not updated on EntityList add/remove methods

### ISSUE THREAD

**Issue by arthef** [shannah/CodeRAD#3]
EntityList extends Entity which extends Observable. My understanding is that the contract on Observable is that hasChanged() is updated every time the Entity is modified.

While this works for Entity as expected, it seems to be not working for EntityList add/remove methods. I looked in the code of EntityList and it seems that the field is not being updated for the list modifications.

It seems that EntityList took a different approach to rely on event handlers and fires an action event when the list is modified. This makes sense and is probably better than relying on hasChanged() but it is different from underlying Entity behavior and inconsistent.

I suggest to unify behavior for Entity and EntityList and make them behave the same way to monitor modifications. Either through hasChanged() or action events. I guess adding hasChanged() to EntityList would be simplest solution right now.

**Comment by shannah** [comment]
Fixed.  Not doing a rebuild yet... but this will be part of the next build.
