### ISSUE TITLE
Displaying ordered collections

### ISSUE THREAD

**Issue by arthef** [shannah/CodeRAD#8]
Currently EntityEditor displays entities from provided EntityList without any specific order. That is last added entity to the list is last displayed.
However, in some use cases it would be highly desirable to control order in which entities are displayed.

I am not sure what would be the best way to add/allow for ordering entities. Would it be EntityList with ordering API or EntityEditor with API for sorting entities.

Actually my current use case is even simpler than this. I just need to add new items to the top of the list. So, EntityList with a method to add a new element at position 0 would be good enough.

**Comment by shannah** [comment]
Yes, you're right. I think an `insert(index, Object item)` method and relevant property change events would solve this case.  Do you agree, of do you need something more?

**Comment by arthef** [comment]
This would solve my current problem with adding elements on top of the list. But I would consider it more as a workaround rather than solution. I am sure, down the road I will need to add elements in the middle according to specific order. And then ordering elements with just ```insert(index, item)``` would be very tedious and inefficient work.

Other issues I had was to avoid duplicates and I had to add special code to make sure there are no duplicates. This code would not be necessary if the API allowed for a a sorted collections or custom collections to be used.

I think the best solution would be some API for a custom comparator or better yet to have API to set a custom backing collection to the EntityList. This would give most flexibility.

**Comment by arthef** [comment]
Hi again. Could you, please let me know what your plans for this are? I am not pushing you to any approach. I just need to know what I can expect and when to plan my development.

**Comment by shannah** [comment]
Hi Artur,
I haven't had a chance to really dig into this.  I've been debugging a critical issue the past few days and haven't been able to think of anything else.

**Comment by shannah** [comment]
I think the best thing to do here is to add the insert() method to the EntityList class.
Then create a subclass OrderedEntityList that overrides includes a Comparator, and overrides the add() method so that it actually calls insert() at the correct location.

This way we can keep the property change events to a minimum, and still provide the ability for views to stay in sync with the model without having to completely purge and re-layout itself.

**Comment by arthef** [comment]
Having just ```insert(atIndex)``` method makes it inefficient to implement sorted collections.

Extending ```EntityList``` would be probably the best solution and then, theoretically we would not need to add any additional API to ```EntityList```. I was looking at possibility to extend ```EntityList``` to make some kind of ```SortedEntityList```. However, I had a few doubts about it:
1. Currently ```entities``` field in ```EntityList``` is private and hardcoded to ```ArrayList```. There is no way to reuse this collection in extending class. So I would need to create a somewhat duplicate field with my own collection. While not a huge problem itself, it leads to some other problems below...
2. All current methods in EntityList use the private ```entities``` field. As a result I would need to duplicate all the methods in my extending class, even if the code would be identical. Again not a huge problem itself as long as you do not change ```EntityList``` logic in the future.
3. The main problem I have is, how would logic using ```EntityList``` like ```EntityEditor``` and ```NodeList``` handle the case when an entity is inserted in the middle of the collection. Would they handle it correctly and reorder UI elements accordingly?

I looked at the ```EntityList``` code and what is really missing there would be the following:
1. Allow for setting a custom List implementation for ```entities``` field
2. Slightly change the ```void add(T link)``` method so it would handle the following:
  - make sure the link was added to the collection. That is checking status of the ```entities.add(link)``` call. If it returns ```false``` element is not added and so skip the rest of the processing.
  - if adding element was successful, checks the index of the added element and call ```fireEntityAdded``` with the actual element index instead of the collection size.
  - make sure the rest of the APIs correctly handle adding elements in the middle of the collection (EntityEditor, NodeList).

With the above changes, customizing the EntityList would be relatively easy with just adding a own/custom list implementation.

**Comment by shannah** [comment]
I have added a protected method for creating the internal collection.

https://shannah.github.io/CodeRAD/javadoc/com/codename1/rad/models/EntityList.html#createInternalList--

You can override this method in EntityList to provide whatever collection you want, just as you described.  This should solve your issue.  Since Java doesn't have a SortedList class, you'll have to implement your own subclass of AbstractList that is sorted - but there are lots of examples around the net on how to do this.

**Comment by arthef** [comment]
Thanks a lot for this. It really makes it easier for me.

Just one small request though. 

With your changes I could have sorted EntityList without really extending the EntityList class. Everything I need is already there. However, as with your current changes I do need to extend the class to provide custom list, just for that. Do you think you could also add a constructor to provide a custom list implementation? This way, there would be no need to extend EntityList.

**Comment by shannah** [comment]
OK.  I've added another constructor for you to provide the internal list.  I fear I may regret this, but, for now it will allow you to do what you need.

**Comment by arthef** [comment]
Thanks a lot! I hope you won't regret it. If I encounter any problems with this approach I will let you know with ideas for solutions.

**Comment by shannah** [comment]
Sounds good.  

The talk of "regret" is purely dogmatic fear.  I've recently adopted a rule of thumb to not expose collections classes in public APIs.  I read this "tip" from one of those old software engineering gurus and have found this practice to make development more enjoyable.  Mostly this advice is targeted at not returning `List<MyClass>`, but rather create a wrapper class called `MyClassList` (or something) as a collection for `MyClass`.  This way when you need to add functionality to perform on sets of MyClass, your codebase isn't littered with different types of collections .. you can just add the required functionality to `MyClassList`.

This doesn't directly speak to the case of taking a collection as a parameter, but I worry one day I'll be faced with a situation switch on a light for me of why this rule should apply to parameters as well.

**Comment by arthef** [comment]
Hehe, thank you for your comments. With my 30+ years of software development I might be considered "old school software engineer", not sure if "guru" applies though.
I definitely agree with the rule above.

However, in our particular case, I think providing a custom List implementation in constructor is less risky than allowing to provide the List by a method.

A method can potentially be called anytime and replace existing list, theoretically, at the time when the existing list is being processed or contains some elements already. While allowing for some interesting use-case, it may lead to all sorts of hard to diagnose problems.

By providing the custom list at the EntityList creation time, you avoid many of those problems.
